### ISSUE TITLE
Installing svg2tikz for use with Inkscape

### ISSUE THREAD

**Issue by OVivero** [kjellmf/svg2tikz#21]
Hi,

Thank you so much for the extension. This is something that would be very useful for me. I downloaded all three files (tikz_export.py, tikz_export_effect.inx and tikz_export_output.inx) and saved them into the Program Files (x86)\inkscape\shared\extensions folder. The extension didn't appear in the Extensions menu. I also attempted downloading the dependencies (inkex.py, simplepath.py and simplestyle.py) into the same folder (although they were already present), but that didn't help. I am using Inkscape version 0.48.5.  I did this under clean installs of inkscape, and restarting it didn't help.

Any help is appreciated

**Comment by kjellmf** [comment]
See https://github.com/kjellmf/svg2tikz/issues/24#issuecomment-102646844 for a step by step instruction
