### ISSUE TITLE
Add support for images

### ISSUE THREAD

**Issue by kjellmf** [kjellmf/svg2tikz#4]
PNG and JPG images should be exported as

```
\node[...] {\includegraphics{image}};
```

Useful for creating overlays and annotations.

**Comment by aalavandhaann** [comment]
Is it time we close this issue? Now the image export is supported? I refer to PR #43

**Comment by kjellmf** [comment]
You are absolutely right. Thank you for the contribution. 

Implemented in ac0059a5131f1647dd654dc1d9df1162d0ffe582
